Method,Name,Error,Occurrences
GET,/api/user-profile,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 4.246.170.83 timed out. (connect timeout=None)')",1
POST,/auth/login,HTTPError('401 Client Error: UNAUTHORIZED for url: /auth/login'),2
GET,/api/user-profile,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",8
